config/routes.rb
Ligamx::Application.routes.draw do

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout' }

  resources :teams, only: [:index, :show]
  resources :stocks, only: [:create, :update]
  resources :transactions do
    collection { post :accept_bid }
  end
  resources :rankings, only: :index
  resources :schedules, only: [:index, :show]
  resources :bids

  match "portfolio", to: 'portfolio#index', as: 'portfolio'
  match "market", to: 'teams#index', as: 'market'

  match "admin", to: "admin/teams#index"
  namespace :admin do
    resources :teams
    resources :users
    resources :announcements
    resources :stocks
    resources :schedules
  end

  root to: "home#index"

end

app/models/announcement.rb
# == Schema Information
#
# Table name: announcements
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Announcement < ActiveRecord::Base
  attr_accessible :content, :title
end

app/controllers/admin/announcements_controller.rb
class Admin::AnnouncementsController < AdminController

  def index
    @announcements = Announcement.all

    respond_to do |format|
      format.html
      format.json { render json: @teams }
    end
  end

  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html
      format.json { render json: @announcement }
    end
  end

  def edit
    @announcement = Announcement.find(params[:id])
  end

  def create
    @announcement = Announcement.new(params[:announcement])

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to admin_announcements_url, notice: 'Announcement was successfully created.' }
        format.json { render json: @announcement, status: :created, location: @announcement }
      else
        format.html { render action: "new" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to admin_announcements_url, notice: 'Announcement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to admin_announcements_url }
      format.json { head :no_content }
    end
  end
end

app/views/admin/announcements/_form.html.erb
<%= form_for [:admin, @announcement], html: { class: "custom" } do |f| %>

  <div class="row">
    <div class="twelve columns">
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :content %>
      <%= f.text_area :content %>
    </div>
  </div>


  <div class="actions">
    <%= f.submit "Save", class: 'button' %>
  </div>
<% end %>

app/views/admin/announcements/edit.html.erb
<h1>Editing Announcment</h1>

<%= render 'form' %>

app/views/admin/announcements/index.html.erb
<%= link_to 'New Announcement', new_admin_announcement_path, class: 'button right' %>
<h1>Manage Announcements</h1>

<% @announcements.each do |announcement| %>
  <h3><%= announcement.title %></h3>
  <%= raw announcement.content %>

  <%= link_to 'Show', [:admin, announcement] %>
  <%= link_to 'Edit', edit_admin_announcement_path(announcement) %>
  <%= link_to 'Destroy', [:admin, announcement], method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/admin/announcements/new.html.erb
 <h1>Add Announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_announcements_path %>