config/routes.rb
Ligamx::Application.routes.draw do

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout' }

  resources :teams, only: [:index, :show]
  resources :stocks, only: [:create, :update]
  resources :transactions do
    collection { post :accept_bid }
  end
  resources :rankings, only: :index
  resources :schedules, only: [:index, :show]
  resources :bids

  match "portfolio", to: 'portfolio#index', as: 'portfolio'
  match "market", to: 'teams#index', as: 'market'

  match "admin", to: "admin/teams#index"
  namespace :admin do
    resources :teams
    resources :users
    resources :announcements
    resources :stocks
    resources :schedules
  end

  root to: "home#index"

end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Schedule < ActiveRecord::Base
  attr_accessible :name, :weeks_attributes

  has_many :weeks

  accepts_nested_attributes_for :weeks
end

app/controllers/admin/schedules_controller.rb
class Admin::SchedulesController < AdminController
	def index
    @schedules = Schedule.all

    respond_to do |format|
      format.html
      format.json { render json: @schedules }
    end
  end

  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @schedule }
    end
  end

  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html
      format.json { render json: @schedule }
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to [:admin, @schedule], notice: 'Schedule was successfully created.' }
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to [:admin, @schedule], notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to admin_schedules_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all

    respond_to do |format|
      format.html
      format.json { render json: @schedules }
    end
  end

  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @schedule }
    end
  end
end

app/views/admin/schedules/_form.html.erb
<%= nested_form_for [:admin, @schedule] do |f| %>

	<%= f.label :name %>
  <%= f.text_field :name %>
  <hr>
  <div class="row">
  	<div class="six columns centered">
			<%= f.fields_for :weeks %>
			<%= f.link_to_add "Add week", :weeks, class: "button tiny" %>
  	</div>
  </div>
	<hr>
	<%= f.submit "Save", class: "button" %>

<% end %>

app/views/admin/schedules/_matchup_fields.html.erb
<div class="row">
	<div class="four columns">
		<%= f.label :team1_id, "Local" %>
		<%= f.select :team1_id, Team.all.map{|u| [u.name,u.id]} %>
	</div>
	<div class="four columns">
		<%= f.label :team2_id, "Visitante" %>
		<%= f.select :team2_id, Team.all.map{|u| [u.name,u.id]} %>
	</div>
	<div class="four columns">
		<%= f.label :date %>
		<%= f.datetime_select :date %>
	</div>
</div>
<hr>

app/views/admin/schedules/_week_fields.html.erb
<div class="row">
	<div class="two columns">
		<%= f.label :number %>
		<%= f.number_field :number %>
	</div>
	<div class="ten columns">
		<%= f.link_to_remove "remove" %>
	</div>
</div>

<hr>
<%= f.fields_for :matchups %>
<%= f.link_to_add "Add match", :matchups, class: "button tiny" %>
<hr>

app/views/admin/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @schedule] %> |
<%= link_to 'Back', admin_schedules_path %>

app/views/admin/schedules/index.html.erb
<%= link_to 'New Schedule', new_admin_schedule_path, class: 'button right' %>

<h1>Schedules</h1>
<table class="twelve">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.name %></td>
    <td><%= link_to 'Show', [:admin, schedule] %></td>
    <td><%= link_to 'Edit', edit_admin_schedule_path(schedule) %></td>
    <td><%= link_to 'Destroy', [:admin, schedule], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

</table>

app/views/admin/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_schedules_path %>

app/views/admin/schedules/show.html.erb
<h1><%= @schedule.name %></h1>

<dl class="tabs">
	<% @schedule.weeks.each_with_index do |week, i| %>
		<%= content_tag :dd, class: set_active_to_first(week, i) do %>
			<a href="#week<%= week.number %>"><%= week.number %></a>
		<% end %>
	<% end %>
</dl>

	<ul class="tabs-content">
	<% @schedule.weeks.each_with_index do |week, i| %>
		<%= content_tag :li, class: set_active_to_first(week, i), id: "week#{week.number}Tab" do %>
			<% week.matchups_by_day.each do |day, matches| %>
		  	<table class="twelve">
		  		<thead>
		  			<tr>
			  			<th colspan="6" class="centered-text"><%= day %></th>
		  			</tr>
		  		</thead>
		  		<tbody>
		  			<% matches.each do |match| %>
			  			<tr>
								<td><%= match.date.strftime("%H:%M") %></td>
								<td><%= match.team1.name %></td>
								<td><div class="icon <%= match.team1.name.parameterize %>"></div></td>
								<td>vs.</td>
								<td><div class="icon <%= match.team2.name.parameterize %>"></div></td>
								<td><%= match.team2.name %></td>
							</tr>
		  			<% end %>
		  		</tbody>
		  	</table>
			<% end %>
		  <% end %>
	<% end %>
	</ul>
	