config/routes.rb
Ligamx::Application.routes.draw do

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout' }

  resources :teams, only: [:index, :show]
  resources :stocks, only: [:create, :update]
  resources :transactions do
    collection { post :accept_bid }
  end
  resources :rankings, only: :index
  resources :schedules, only: [:index, :show]
  resources :bids

  match "portfolio", to: 'portfolio#index', as: 'portfolio'
  match "market", to: 'teams#index', as: 'market'

  match "admin", to: "admin/teams#index"
  namespace :admin do
    resources :teams
    resources :users
    resources :announcements
    resources :stocks
    resources :schedules
  end

  root to: "home#index"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  credit                 :decimal(, )
#  username               :string(255)
#

class User < ActiveRecord::Base
  rolify

	attr_accessible :email, :password, :password_confirmation, :remember_me, :credit, :username, :login
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true

  has_many :bids
  has_many :stocks
  has_many :transactions

  attr_accessor :login

  def buy_stock(team_id, team_value)
		stock = stocks.build(team_id: team_id, price: team_value)
  	stock
  end

  def sell_stock(stock_id)
    stock = stocks.find(stock_id)
    transaction = transactions.build(stock_id: stock_id)
    if stock.quantity > 0
      stock.quantity -= 1
      transaction.update_attributes(initial_value: stock.price, final_value: stock.team.current_value, roi: stock.transaction_return)
    else
      errors.add(:base, 'You can not sell this stock.')
      return false
    end
    transaction
    stock
  end

  def accept_bid(stock_id)
    stock = stocks.find(stock_id)
    transaction = transactions.build(stock_id: stock_id)
    bid = stock.team.bids.first
    new_stock = Stock.create(team_id: stock.team.id, price: bid.price, user_id: bid.user_id, quantity: 1)
    if stock.quantity > 0
      stock.quantity -= 1
      transaction.update_attributes(initial_value: stock.price, final_value: stock.team.bids.first.price, roi: stock.transaction_return_on_bid)
      bid.update_attributes(accepted: true)
    else
      errors.add(:base, 'You can not sell this stock.')
      return false
    end
    transaction
    new_stock
    stock
  end

  def initial_available_credit
    return 300
  end

  def self.order_by_portfolio
    users = all
    users = users.sort { |a,b| b.total_portfolio_value <=> a.total_portfolio_value}
  end

  def self.top_ten
    order_by_portfolio.first(10)
  end

  def credit_spent_on_bids
    bids.to_a.sum { |bid| bid.price }
  end

  def total_return_percentage
    100 * (total_portfolio_value - initial_available_credit) / initial_available_credit
  end

  def total_portfolio_value
    current_portfolio_value + available_credit + credit_spent_on_bids
  end

  def transaction_gains
    transactions.to_a.sum { |transaction| transaction.roi }
  end

  def available_credit
    initial_available_credit - total_credit_spent + total_credit_earned - original_portfolio_value - credit_spent_on_bids
  end

  def current_portfolio_value
    stocks.to_a.sum { |stock| stock.quantity * stock.team.current_value }
  end

  def original_portfolio_value
    stocks.to_a.sum { |stock| stock.quantity * stock.price }
  end

  def current_portfolio_gains
    current_portfolio_value - original_portfolio_value
  end

  def total_credit_spent
    transactions.to_a.sum { |transaction| transaction.initial_value }
  end

  def total_credit_earned
    transactions.to_a.sum { |transaction| transaction.final_value }
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
	def index
    @users = User.all

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin, @user], notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>

<div class="row">
	<div class="ten columns">

		<%= f.label :username %>
	  <%= f.email_field :username %>

		<%= f.label :email %>
	  <%= f.email_field :email %>

	  <%= f.label :password %>
	  <%= f.password_field :password %>

	  <%= f.label :password_confirmation %>
	  <%= f.password_field :password_confirmation %>
	</div>

	<div class="two columns">
		<%= f.label :credit %>
	  <%= f.number_field :credit %>
	</div>	
</div>

<div><%= f.submit "Save", class: "button" %></div>

<% end %>

app/views/admin/users/_portfolio.html.erb
<h3>Acciones</h3>
<table class="twelve responsive">
	<thead>
		<tr>
			<th>#</th>
			<th></th>
			<th>Equipo</th>
			<th>Valor Compra</th>
			<th>Valor Actual</th>
			<th>Total Compra</th>
			<th>Total Actual</th>
			<th>Gain / Loss</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% Stock.grouped_by_team_and_price(@user).each do |stock| %>
			<tr>
				<td><%= stock.total_quantity %></td>
		    <td><div class="icon <%= stock.team.name.parameterize %>"></div></td>
				<td><%= link_to stock.team.name, stock.team %></td>
				<td><%= number_to_currency(stock.price) %></td>
				<td><%= number_to_currency(stock.team.current_value) %></td>
				<td><%= number_to_currency(stock.total_purchase_value) %></td>
				<td><%= number_to_currency(stock.total_current_value) %></td>
				<td class="<%= gain_loss(stock.investment_return) %>"><%= number_to_currency(stock.investment_return) %></td>
				<td>
					<div class="sell">
						<%= button_to "Sell", transactions_path(stock_id: stock), class: 'button', id: 'sell_button', form: { "data-team" => stock.team.name }, disable_with: 'Selling...' unless stock.team.match_right_now? %>
					</div>
				</td>
			</tr>
		<% end %>
	</tbody>
	<tfoot>
		<tr>
			<td colspan="6"></td>
			<td><%= number_to_currency(@user.current_portfolio_value) %></td>
			<td class="<%= gain_loss(@user.current_portfolio_gains) %>"><%= number_to_currency(@user.current_portfolio_gains) %></td>
			<td></td>
		</tr>
	</tfoot>
</table>

app/views/admin/users/_transactions.html.erb
<h3>Ventas</h3>
<table class="twelve responsive">
	<thead>
		<tr>
			<th>Equipo</th>
			<th>Precio Compra</th>
			<th>Precio Venta</th>
			<th>Gain / Loss</th>
			<th>Fecha</th>
		</tr>
	</thead>
	<tbody>
		<% @user.transactions.each do |transaction| %>
		<tr>
			<td><%= transaction.stock.team.name %></td>
			<td><%= number_to_currency(transaction.initial_value) %></td>
			<td><%= number_to_currency(transaction.final_value) %></td>
			<td class="<%= gain_loss(transaction.roi) %>"><%= number_to_currency(transaction.roi) %></td>
			<td><%= transaction.created_at.to_formatted_s(:long)  %></td>
		</tr>
		<% end %>
	</tbody>
	<tfoot>
		<tr>
			<td colspan="3"></td>
			<td class="<%= gain_loss(@user.transaction_gains) %>"><%= number_to_currency(@user.transaction_gains) %></td>
		</tr>
	</tfoot>
</table>

app/views/admin/users/index.html.erb
<%= link_to 'New User', new_admin_user_path, class: 'button right' %>

<h1>Users</h1>
<h6><%= @users.size %> registered users.</h6>
<table class="twelve">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>SignIn Count</th>
      <th>Current Sign In</th>
      <th>Last Sign In</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.sign_in_count %></td>
    <td><%= user.current_sign_in_at %></td>
    <td><%= user.last_sign_in_at %></td>
    <td><%= link_to 'Show', [:admin, user] %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
    <td><%= link_to 'Destroy', [:admin, user], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

</table>

app/views/admin/users/new.html.erb
 <h1>New user</h1>

<div class="row">
	<div class="five columns centered">
		<%= render 'form' %>
	</div>
</div>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<div class="row">
	<div class="twelve columns">
		<h3><%= @user.username.nil? ? "Inversionista" : @user.username %> <small><%= link_to 'Edit profile', edit_user_registration_path %></small></h3>
	</div>
</div>


<div class="row">
	<div class="three columns">
		<!-- <li>
			<div class="panel">
				<h4><%#= @user.ranking %></h4>
				<p><strong>Ranking</strong></p>
			</div>
		</li> -->
		
		<%= link_to 'https://en.gravatar.com/site/signup/', class: 'th' do %>
			<%= gravatar_for @user, 220 %>
		<% end %>
		<h6><%= link_to 'Add avatar', 'https://en.gravatar.com/site/signup/' %></h6>
		<hr>

		<div class="panel">
			<h4><%= number_to_currency(@user.available_credit) %> <small></small></h4>
			<h4><small>Efectivo</small></h4>
		</div>
		<div class="panel">
			<h4><%= number_to_currency(@user.total_portfolio_value) %></h4>
			<h4><small>Valor Portafolio</small></h4>
		</div>
		<div class="panel">
			<h4 class="<%= gain_loss(@user.total_return_percentage) %>"><%= number_to_percentage(@user.total_return_percentage) %></h4>
			<h4><small>Rendimiento</small></h4>
		</div>
	</div>
	
	<div class="nine columns">
		<dl class="tabs">
		  <dd class="active"><a href="#portfolio">Acciones</a></dd>
		  <dd><a href="#sales">Ventas</a></dd>
		</dl>

		<ul class="tabs-content">
		  <li class="active" id="portfolioTab">
		  	<%= render 'portfolio' %>
		  </li>
		  <li id="salesTab">
		  	<%= render 'transactions' %>
		  </li>
		</ul>
	</div>
</div>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>