config/routes.rb
Ligamx::Application.routes.draw do

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout' }

  resources :teams, only: [:index, :show]
  resources :stocks, only: [:create, :update]
  resources :transactions do
    collection { post :accept_bid }
  end
  resources :rankings, only: :index
  resources :schedules, only: [:index, :show]
  resources :bids

  match "portfolio", to: 'portfolio#index', as: 'portfolio'
  match "market", to: 'teams#index', as: 'market'

  match "admin", to: "admin/teams#index"
  namespace :admin do
    resources :teams
    resources :users
    resources :announcements
    resources :stocks
    resources :schedules
  end

  root to: "home#index"

end

app/views/layouts/_admin_navigation.html.erb
<div class="row">
  <div class="twelve columns">
    <nav class="top-bar">
      <ul>
        <!-- Title Area -->
        <li class="name">
          <h1>
            <a href="#">
              Admin
            </a>
          </h1>
        </li>
        <li class="toggle-topbar"><a href="#"></a></li>
      </ul>

      <section>
        <!-- Left Nav Section -->
        <ul class="left">
          <li class="divider"></li>
            <li><%= link_to "Announcements", admin_announcements_path %></li>
          <li class="divider"></li>
            <li><%= link_to "Users", admin_users_path %></li>
          <li class="divider"></li>
            <li><%= link_to "Teams", admin_teams_path %></li>
          <li class="divider"></li>
            <li><%= link_to "Schedules", admin_schedules_path %></li>
          <li class="divider"></li>
          
        </ul>

        <!-- Right Nav Section -->
        <% if user_signed_in? %>
        <ul class="right">
          <li class="divider show-for-medium-and-up"></li>        
          <li class="has-dropdown">
            <a href="#"><%= current_user.email %></a>
            <ul class="dropdown">
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
        <% end %>
      </section>
    </nav>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="twelve columns">
    <hr />
    <div class="row">
      <div class="six columns">
        <p>&copy; Ijooooo.</p>
      </div>
      <div class="six columns">
        <a href="http://mixpanel.com/f/partner" class="right">
        	<img src="http://mixpanel.com/site_media/images/partner/badge_blue.png" alt="Real Time Web Analytics" />
        </a>
      </div>
    </div>
  </div> 
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert-box <%= name == :notice ? "success" : "alert" %>">
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/layouts/_mixpanel.html.erb
<!-- start Mixpanel --><script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==
typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.increment people.append people.track_charge".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2}})(document,window.mixpanel||
[]);
mixpanel.init("<%= MIXPANEL_TOKEN %>");</script><!-- end Mixpanel -->

app/views/layouts/_navigation.html.erb
<div class="row">
  <div class="twelve columns">
    <nav class="top-bar">
      <ul>
        <!-- Title Area -->
        <li class="name">
          <h1>
            <%= link_to "BMF", root_path %>
          </h1>
        </li>
        <li class="toggle-topbar"><a href="#"></a></li>
      </ul>

      <section>
        <!-- Left Nav Section -->
        <ul class="left">
          <li class="divider"></li>
            <li><%= link_to "Portfolio", portfolio_path %></li>
          <li class="divider"></li>
            <li><%= link_to "Market", market_path %></li>
          <li class="divider"></li>
            <li><%= link_to "Rankings", rankings_path %></li>
          <li class="divider"></li>
            <li><%= link_to "Schedule", schedules_path %></li>
          <li class="divider"></li>
          
        </ul>

        <!-- Right Nav Section -->
        <% if user_signed_in? %>
        <ul class="right">
          <li class="divider show-for-medium-and-up"></li>        
          <li class="has-dropdown">
            <a href="#"><%= current_user.username.nil? ? current_user.email : current_user.username %></a>
            <ul class="dropdown">
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
        <% end %>
      </section>
    </nav>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>

<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "Admin" %></title>
  
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>

<body>
	<div class="row">
		<div class="twelve columns">
			<%= render 'layouts/admin_navigation' %>
			<%= render 'layouts/messages' %>
			<%= yield %>
		</div>
	</div>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=7" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "Bolsa Mexicana de Fútbol" %></title>
  
  <%= tag :meta, name: "user_email", :content => current_user.email if user_signed_in? %>
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/mixpanel' %>
</head>

<body>

	<%= render 'layouts/navigation' if user_signed_in? %>

	<div class="row">
		<div class="twelve columns">
			<%= render 'layouts/messages' %>
			<%= yield %>
		</div>
	</div>

	<%= render 'layouts/footer' %>
  <%= analytics_init if Rails.env.production? %>
</body>
</html>